# Generated by Django 5.0.3 on 2024-03-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_rename_date_created_blog_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
